#!/usr/bin/env python

import sys
import Quartz

search = ' '.join(sys.argv[1:])

wl = Quartz.CGWindowListCopyWindowInfo(Quartz.kCGWindowListOptionAll, Quartz.kCGNullWindowID)
for v in wl:
    title = v.valueForKey_('kCGWindowName')
    if title is not None and len(title) is not 0:
        if search in title and not 'findWindow' in title:
            print str(v.valueForKey_('kCGWindowNumber'))
            quit()
